version: "3.8"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory_control_db
    volumes:
      - pg-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-db:
